type Discipline {
  _id: ID!
  name: String!
  teacher: Teacher!
}

input CreateDisciplineInput {
  name: String!
  teacher: ID!
}

input UpdateDisciplineInput {
  name: String
  teacher: ID
}

type Query {
  disciplines: [Discipline!]!
  discipline(id: ID!): Discipline!
}

type Mutation {
  createDiscipline(data: CreateDisciplineInput!): Discipline!
  updateDiscipline(id: ID!, data: UpdateDisciplineInput!): Discipline!
  deleteDiscipline(id: ID!): Boolean
}
